# -*- coding: utf-8 -*-
"""project 110

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xDDwE3WJ5S7n7Q-ZpjVKYsESztND5b8_
"""

from google.colab import files
data_to_load = files.upload()

import statistics
import csv
import pandas as pd
import random
import plotly.figure_factory as ff

df = pd.read_csv("medium_data.csv")
data = df["claps"].tolist()

meanClaps = statistics.mean(data)
print(meanClaps)

def takeData(counter):
  dataset = []
  for i in range(0, counter):
    random_index = random.randint(0, len(data)-1)
    value = data[random_index]
    dataset.append(value)
  mean = statistics.mean(dataset)
  return mean


def repeat():
  meanList=[]
  for i in range(0,100):
    set_of_means = takeData(30)
    meanList.append(set_of_means)
  show_fig(meanList)
  return meanList


def show_fig(meanList):
    fig = ff.create_distplot([meanList], ["claps"], show_hist = False)
    fig.show()


lists  = repeat()
show_fig(lists)

